import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { COMMANDS, contractMethods } from '../dist/commands.js';
import { CONTRACT_ABIS, indexerShapes } from '@daoships/sdk';
await chmod(new URL('../dist/bin.js', import.meta.url), 0o755);
await mkdir(new URL('../docs/', import.meta.url), { recursive: true });
const commands = COMMANDS.map(({ run, ...command }) => command);
await writeFile(new URL('../docs/commands.json', import.meta.url), JSON.stringify({ schemaVersion: 1, commands }, null, 2) + '\n');
const contracts = Object.keys(CONTRACT_ABIS).map(kind => ({ kind, methods: contractMethods(kind) }));
const escape = s => String(s).replaceAll('|', '\\|');
const lines = ['# Command reference', '', 'Generated by `npm run build` from the same registry used by the CLI and TUI.', '',
  'Every positional command also accepts `daoships run "command path" \'{"field":"value"}\'`. JSON fields accept `@file.json` in either interface. Global flags work before or after subcommands.', '',
  '| Command | Effect | Purpose |', '| --- | --- | --- |',
  ...commands.map(c => `| \`${c.path} ${c.fields.map(f => f.optional ? `[${f.name}]` : `<${f.name}>`).join(' ')}\` | ${c.effect} | ${escape(c.description)} |`),
  '', '# Contract coverage', '', '| Contract | Reads | Writes |', '| --- | ---: | ---: |',
  ...contracts.map(c => `| ${c.kind} | ${c.methods.filter(m => m.effect === 'read').length} | ${c.methods.filter(m => m.effect === 'write').length} |`),
  '', `${contracts.reduce((n, c) => n + c.methods.length, 0)} ABI functions across ${contracts.length} contracts. ${Object.keys(indexerShapes).length} indexed tables.`, '',
  'Use `contract methods <kind>` or `navigator methods <kind>` for canonical signatures, input types, mutability and overloads. In the TUI, press **a** on a DAO or navigator to open those same methods as guided forms.', '',
];
await writeFile(new URL('../docs/commands.md', import.meta.url), lines.join('\n'));
